#pragma once

enum ERROR_CODE {
    NO_ERROR,
    USAGE_ERROR,
    FILE_ERROR,
    LEX_ERROR,
    SYNTAX_ERROR,
    AST_BUILD_ERROR,
    NO_MAIN_ERROR,
    EMPTY_AST_ERROR,
    UNKNOWN_VARIABLE_ERROR,
    OTHER_ERROR
};
